apiVersion: v1
kind: Service
metadata:
  name: python-devsecops-service
  namespace: python-devsecops
spec:
  selector:
    app: python-devsecops-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: ClusterIP
